// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8POGpFy_x-JuOf4Mqi9aNxw1hmhS5hU8',
    appId: '1:999797836328:web:8d9c8c11e5563bebf3431d',
    messagingSenderId: '999797836328',
    projectId: 'fir-e-eb17a',
    authDomain: 'fir-e-eb17a.firebaseapp.com',
    storageBucket: 'fir-e-eb17a.appspot.com',
    measurementId: 'G-KG8YB91998',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARwLvUPdgx88hc1_I4frn4q5CSkNCmqxI',
    appId: '1:999797836328:android:91a55ccde0fc638ef3431d',
    messagingSenderId: '999797836328',
    projectId: 'fir-e-eb17a',
    storageBucket: 'fir-e-eb17a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAim5hEdd9NGRCq4B8ysqYjmp8V5yrCbO8',
    appId: '1:999797836328:ios:dd7b7dd2c70a6a65f3431d',
    messagingSenderId: '999797836328',
    projectId: 'fir-e-eb17a',
    storageBucket: 'fir-e-eb17a.appspot.com',
    iosBundleId: 'com.example.firebase',
  );
}
